import os


module data:
    snakefile:
        os.path.join("rules", "data.smk")
    config:
        config


module demux:
    snakefile:
        os.path.join("rules", "demux.smk")
    config:
        config


module qc:
    snakefile:
        os.path.join("rules", "qc.smk")
    config:
        config


module vis_feature_tbl:
    snakefile:
        os.path.join("rules", "vis_feature_tbl.smk")
    config:
        config


use rule * from data


use rule * from demux


use rule * from qc


use rule * from vis_feature_tbl


rule all:
    input:
        rules.data_all.input,
        rules.demux_all.input,
        rules.qc_all.input,
        rules.vis_feature_tbl_all.input,
    default_target: True
