import os


include: "rules/data.smk"
include: "rules/demux.smk"
include: "rules/qc.smk"
include: "rules/vis_feature_tbl.smk"
include: "rules/phylo_tree.smk"
include: "rules/diversity_analysis.smk"


rule all:
    input:
        rules.data_all.input,
        rules.demux_all.input,
        rules.qc_all.input,
        rules.vis_feature_tbl_all.input,
        rules.generate_phylogeny_tree.output,
        rules.diversity_analysis_all.input,
    default_target: True
